cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/30-8/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC36.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/14-8/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC56.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/14-3/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC52.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/28-L2/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC8.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/24-L1/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC3.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/15-4/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC18.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/14-5/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC54.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/14-6/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC55.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/28-L1/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC7.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/14-2/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC51.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/15-5/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC19.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/30-1/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC30.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/25-5/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC26.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/25-3/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC25.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/15-1/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC16.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/9-8/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC15.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/7-2/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC38.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/12-6/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC48.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/25-2/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC24.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/25-1/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC23.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/22-L1/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC1.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/30-3/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC32.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/25-L2/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC6.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/12-2/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC46.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/15-8/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC22.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/12-1/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC45.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/15-3/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC17.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/15-6/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC20.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/9-2/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC10.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/25-6/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC27.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/7-4/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC40.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/25-7/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC28.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/12-3/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC47.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/30-7/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC35.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/7-10C5/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC41.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/30-4/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC33.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/9-6/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC13.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/22-L2/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC2.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/30-5/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC34.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/7-3/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC39.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/9-1/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC9.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/25-L1/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC5.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/9-4/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC12.txt
cp /datb/fanxiaoying/project/project04_RNA_chip/01.pipeline/9-3/genes.fpkm_tracking /datb/fanxiaoying/project/project04_RNA_chip/GEO/for_shen/FPKM_mESC11.txt
